### ISSUE TITLE
I have some problem when running the project

### ISSUE THREAD

**Issue by SYuan03** [melifluos/subgraph-sketching#17]
I am nearly mad. I spent the whole afternoon trying to run the code, but it seems that I can't execute it according to the given instructions now. It seems that we should use "pip install torch-geometric" instead of "conda install pyg -c pyg" on gpu.I don't know why. Can someone tell me about the difference?

**Comment by WXU-M** [comment]
My versions are all correct, but I keep getting this error, "FileNotFoundError: Could not find module 'D:\Anacondas\envs\ss1\Lib\site-packages\torch_sparse\_convert_cuda.pyd' (or one of its dependencies). Try using the full path with the constructor syntax."

**Comment by melifluos** [comment]
Hi both, apologies for the delayed reply. Were you able to fix this issue? As of version 2.0 pyg is a lot easier to install than it used to be when you had to match the cuda versions

**Comment by SYuan03** [comment]
yeah, thx~

**Comment by SYuan03** [comment]
yeah~thank you
