### ISSUE TITLE
The results in the paper cannot be reproduced

### ISSUE THREAD

**Issue by ZDDWLIG** [melifluos/subgraph-sketching#18]
Thank you for sharing your code！When I reproduced BUDDY's results using the parameter Settings provided, I got a lower result than reported in the paper. There is a 3%-5% decline in almost every dataset. Whether some additional setup is required?

Sincerely

**Comment by SYuan03** [comment]
So do I.

**Comment by melifluos** [comment]
Hi both, this is a result of us losing access to the real hyperparameters when Elon Musk took over at Twitter and lacking the resources to rerun the same hyperparamerter sweeps again. I've updated some of the run instructions so that the OGB results should be exactly reproducible.
