### ISSUE TITLE
Is a node its own neighbour?

### ISSUE THREAD

**Issue by LucaCappelletti94** [melifluos/subgraph-sketching#7]
Hi @melifluos, I have finished an [open-source implementation in Rust of the sketching features described in this paper](https://github.com/AnacletoLAB/ensmallen/blob/hyperball_intersections/graph/cpu_models/src/hyper_sketching.rs), but after I ran it on a graph as sparse as directed WikiData I realized that many if not all features in the leaves are zeros if I consider each node not as part of its neighbourhood, aka introducing self-loops.

I was wondering what was your opinion in the matter, as I am not sure whether your paper suggests including them or not.

I guess I'll just add a flag and the user can decide for himself - as you may find in my implementation I have added the option to ingest as part of the sketch several other features, such as node types and edge types. 

Please find attached the performance of running it on WikiData (over 1 billion nodes a 5 billion edges) on my desktop.

<img width="680" alt="Screenshot 2023-05-31 alle 23 36 01" src="https://github.com/melifluos/subgraph-sketching/assets/7738570/503deb2b-e470-416f-b829-d95a9e095186">

**Comment by melifluos** [comment]
@LucaCappelletti94 this is so cool! Thanks for sharing. 

In answer to your question, you must add self loops. This is done before hashes are generated here
https://github.com/melifluos/subgraph-sketching/blob/main/src/hashing.py#L146
If you don't, then in the trivial case of a graph that contains only 2 connected nodes, you will think that the cardinality of their 1-hop intersection is zero.

**Comment by LucaCappelletti94** [comment]
Perfect, thank you - I have now switched the default flag to true.

**Comment by Barcavin** [comment]
> @LucaCappelletti94 this is so cool! Thanks for sharing.
> 
> In answer to your question, you must add self loops. This is done before hashes are generated here https://github.com/melifluos/subgraph-sketching/blob/main/src/hashing.py#L146 If you don't, then in the trivial case of a graph that contains only 2 connected nodes, you will think that the cardinality of their 1-hop intersection is zero.

Actually, I got a bit more confused about this. For the trivial case you mentioned, isn't that what we want is the cardinality of their 1-hop intersection is zero? since there are only 2 connected nodes, there is 0 common neighbor.

**Comment by LucaCappelletti94** [comment]
I think 90/100 the effectiveness of either choices depend on the graph topology and you'll need to try both out as part of hyperparameter tuning. I am setting up an experimental setup to do exactly that.
